### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by SylvieDoumet** [Rahaf91/capstone-natural-cures#24]
**Value proposition**

As a User I want to add my own remedy recipes. I want to upload my own image in order to have a matching picture for my added recipe.

**Acceptance criteria**

- I want to see a placeholder if no image is uploaded.
- By clicking on the Image-button I can select a picture from my local device.
- I want to see an error message if I use a wrong file format.

**Tasks**

- [ ] Create feature branch `feature/image-upload`
- [ ] Use Cloudinary for storage.
- [ ] Setting up the project via Web Capstone Docs.
- [ ] `https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary`
- [ ] Create a ImageUpload component
- [ ] handleSubmit function to get the data
- [ ] API Route (e.g. /pages/api/upload/index.js).
- [ ] handler function to send image file to Cloudinary
- [ ] Create Upload Image Field in the Add Remedy Form component
