### ISSUE TITLE
#Search Bar

### ISSUE THREAD

**Issue by SylvieDoumet** [Rahaf91/capstone-natural-cures#25]
As a user, I want to search for remedies in order to find an appropriate home remedy for my medical concern.

**Acceptance criteria**

- Search remedy recipes by title
- Show all remedy recipes when search bar is empty
- Show message when no remedies match the search criteria
- Show search results in real-time

**Tasks**

- [ ] Create `feature/searchbar branch`
- [ ] Create SearchBar component
- [ ] Create useState
- [ ] Convert searchInput into lower case
- [ ] Map in `RemediesList.js` through searchInput
- [ ] Return all projects if searchInput is empty

**Comment by JohannMerck** [comment]
Hey, 

just one minor adjustment: perhaps specify the Create useState Task, i.e. what is stored, etc. Otherwise looks good!
