### ISSUE TITLE
##Daily Health Tips

### ISSUE THREAD

**Issue by SylvieDoumet** [Rahaf91/capstone-natural-cures#27]
## Value Proposition
**As a User**
 **I want to** receive daily health and wellness tips on the apps landing page 
**so that** I stay informed and engaged.

## Description

![Image](https://github.com/user-attachments/assets/afb1b362-34f5-4c06-a618-1adb3199d10f)

Carousel with image and tips on the landing page

### Carousel Display 

- The app should display a carousel of 5 daily health tips at the top of the landing page (as first impression of the site)
- The carousel should automatically switch between tips every 2 seconds.
- Each daily health tip should include an image and a short description.

### Placement

- The carousel should be placed underneath the header section, which contains the filter options and search bar.
- The carousel should be displayed above the main section (list of remedy recipes)

## Tasks 

- [ ] Create a feature branch `feature/daily-healthtips`
- [ ] Create a DailyHealthTips.json file containing an array of objects for the health tips. 
- [ ] Develop a carousel component that fetches data from the JSON file and displays it. 
- [ ] Implement automatic switching between tips every 2 seconds.
- [ ] Add the carousel component to RemediesList.js and ensure it’s displayed between the header and main content section.
- [ ] Update app.js / [id].js to support the new feature.
